import Layout from "@/components/Layout";
import { FileText, CheckCircle, ExternalLink, Phone, Camera, BarChart2, List } from "lucide-react";

const sampleReports = [
  {
    id: 1,
    label: "Sample Report 1",
    title: "Buyer Home Inspection",
    desc: "A full buyer's inspection report showing how we document every system and component — roof to foundation — with photos, priority rankings, and clear findings.",
    url: "https://app.spectora.com/home-inspectors/my-inspection-company-2bb70fdb44/sample_report?sample_id=40490",
  },
  {
    id: 2,
    label: "Sample Report 2",
    title: "Buyer Home Inspection",
    desc: "Another example of our comprehensive buyer inspection report. See how we present findings, photograph defects, and prioritize items for your real estate agent and contractors.",
    url: "https://app.spectora.com/home-inspectors/my-inspection-company-2bb70fdb44/sample_report?sample_id=40491",
  },
  {
    id: 3,
    label: "Sample Report 3",
    title: "Buyer Home Inspection",
    desc: "A third sample showing the depth and consistency of our reporting. Every inspection follows the same thorough process — delivered digitally within 24 hours.",
    url: "https://app.spectora.com/home-inspectors/my-inspection-company-2bb70fdb44/sample_report?sample_id=40492",
  },
];

const reportFeatures = [
  { icon: Camera, title: "Photo Documentation", desc: "Every issue is photographed and clearly labeled so you can see exactly what we found." },
  { icon: List, title: "Priority Rankings", desc: "Issues are categorized by severity — safety concerns, major defects, and maintenance items." },
  { icon: BarChart2, title: "Summary Section", desc: "A clear executive summary gives you the key findings at a glance before diving into details." },
  { icon: FileText, title: "Digital Delivery", desc: "Reports are delivered digitally within 24 hours and accessible on any device." },
];

export default function SampleReports() {
  return (
    <Layout>
      <div className="bg-[oklch(0.12_0.005_260)] py-16 border-b border-white/5">
        <div className="container">
          <div className="section-label mb-4">Sample Reports</div>
          <h1 className="font-['Barlow_Condensed'] font-800 text-5xl md:text-6xl text-white leading-tight mb-4">
            See What You'll Receive
          </h1>
          <p className="text-muted-foreground max-w-2xl text-lg leading-relaxed">
            Browse real sample reports generated by True Homes Inspections. See exactly how we document findings, photograph defects, and deliver results within 24 hours.
          </p>
        </div>
      </div>

      {/* Sample Report Cards */}
      <section className="py-20 bg-background">
        <div className="container">
          <div className="section-label mb-4">Live Sample Reports</div>
          <h2 className="font-['Barlow_Condensed'] font-800 text-4xl text-white mb-3">
            View Real Inspection Reports
          </h2>
          <div className="amber-divider mb-10" />
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
            {sampleReports.map((report) => (
              <div key={report.id} className="bg-[oklch(0.15_0.005_260)] border border-white/8 flex flex-col">
                {/* Header bar */}
                <div className="bg-[#D35400]/10 border-b border-[#D35400]/20 px-6 py-4 flex items-center gap-3">
                  <div className="w-8 h-8 bg-[#D35400]/20 flex items-center justify-center flex-shrink-0">
                    <FileText size={16} className="text-[#D35400]" />
                  </div>
                  <div>
                    <div className="text-[#D35400] font-['Barlow_Condensed'] font-700 text-xs tracking-widest uppercase">
                      {report.label}
                    </div>
                    <div className="text-white font-['Barlow_Condensed'] font-700 text-base leading-tight">
                      {report.title}
                    </div>
                  </div>
                </div>
                {/* Body */}
                <div className="p-6 flex flex-col flex-1">
                  <p className="text-sm text-muted-foreground leading-relaxed mb-6 flex-1">
                    {report.desc}
                  </p>
                  <a
                    href={report.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-amber text-xs flex items-center justify-center gap-2 w-full"
                  >
                    <ExternalLink size={13} /> View Full Report
                  </a>
                </div>
              </div>
            ))}
          </div>

          {/* Report features + checklist */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-start">
            <div>
              <div className="section-label mb-4">Report Features</div>
              <h2 className="font-['Barlow_Condensed'] font-800 text-4xl text-white mb-6">
                Detailed, Clear, Actionable Reports
              </h2>
              <div className="amber-divider mb-6" />
              <p className="text-muted-foreground leading-relaxed mb-6">
                Our inspection reports are generated using Spectora — industry-leading inspection software — and include hundreds of photos, clear descriptions of every finding, and priority rankings that help you understand what matters most.
              </p>
              <p className="text-muted-foreground leading-relaxed mb-8">
                Unlike some inspectors who deliver vague, text-only reports, we provide visual documentation of every issue we find. You'll know exactly what you're dealing with — and so will your real estate agent and any contractors you hire for repairs.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-8">
                {reportFeatures.map((feature) => (
                  <div key={feature.title} className="service-card">
                    <div className="w-8 h-8 bg-[#D35400]/10 flex items-center justify-center mb-3">
                      <feature.icon size={16} className="text-[#D35400]" />
                    </div>
                    <h3 className="font-['Barlow_Condensed'] font-700 text-base text-white mb-1">{feature.title}</h3>
                    <p className="text-xs text-muted-foreground leading-relaxed">{feature.desc}</p>
                  </div>
                ))}
              </div>
              <div className="bg-[oklch(0.20_0.005_260)] border border-[#D35400]/20 p-5">
                <h3 className="font-['Barlow_Condensed'] font-700 text-lg text-white mb-3">Questions About Reports?</h3>
                <p className="text-sm text-muted-foreground mb-4">Want Tim to walk you through a report before you schedule? Just call.</p>
                <a href="tel:+12082439706" className="btn-amber text-xs flex items-center gap-2 w-full justify-center">
                  <Phone size={13} /> Call Tim — 208-243-9706
                </a>
              </div>
            </div>

            <div>
              <div className="bg-[oklch(0.20_0.005_260)] border border-white/5 p-8">
                <h3 className="font-['Barlow_Condensed'] font-700 text-xl text-white mb-6">What's in Every Report</h3>
                <ul className="space-y-3">
                  {[
                    "Executive summary of key findings",
                    "Detailed findings for all major systems",
                    "Hundreds of labeled photographs",
                    "Safety concern callouts",
                    "Major defect identification",
                    "Maintenance recommendation items",
                    "Repair priority rankings",
                    "Estimated repair cost ranges (where applicable)",
                    "Inspector notes and observations",
                    "Recommendations for further evaluation",
                    "Digital delivery within 24 hours — guaranteed",
                    "Accessible on any device (phone, tablet, computer)",
                  ].map((item) => (
                    <li key={item} className="flex items-start gap-3 text-sm text-white/70">
                      <CheckCircle size={13} className="text-[#D35400] flex-shrink-0 mt-0.5" />
                      {item}
                    </li>
                  ))}
                </ul>
                <div className="mt-8 pt-6 border-t border-white/5">
                  <a href="tel:+12082439706" className="btn-amber w-full justify-center text-xs flex items-center gap-2">
                    <Phone size={13} /> Call Tim Now
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="py-16 bg-[#D35400]">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-6">
          <div>
            <h2 className="font-['Barlow_Condensed'] font-800 text-3xl text-[oklch(0.10_0.005_260)] leading-tight mb-1">
              Ready for Your Detailed Report?
            </h2>
            <p className="text-[oklch(0.10_0.005_260)]/70 text-sm">Schedule your inspection and receive your report within 24 hours.</p>
          </div>
          <a href="tel:+12082439706" className="bg-[oklch(0.10_0.005_260)] text-white font-['Barlow_Condensed'] font-700 text-sm tracking-widest uppercase px-8 py-4 hover:bg-[oklch(0.20_0.005_260)] transition-colors flex items-center gap-2 flex-shrink-0">
            <Phone size={14} /> Call Tim — 208-243-9706
          </a>
        </div>
      </section>
    </Layout>
  );
}
